# ===========================================
# Dokploy Docker Compose Configuration
# ===========================================
# Cấu hình này được tối ưu cho Dokploy deployment
# Đảm bảo dữ liệu tài khoản Zalo được bảo toàn qua các lần deploy

version: "3.8"
services:
  zalo-server:
    # Image từ registry (replace with your registry)
    image: ${DOCKER_IMAGE:-ghcr.io/chickenai/multizlogin:latest}
    
    ports:
      - "${PORT:-3000}:3000"
    
    # Sử dụng named volume cho persistent storage
    # QUAN TRỌNG: Volume này giữ dữ liệu qua các lần deploy
    volumes:
      - multizlogin-data:/app/data
    
    environment:
      # Server config
      - PORT=${PORT:-3000}
      - NODE_ENV=production
      - DATA_PATH=/app/data
      
      # Session secret - QUAN TRỌNG: Thay đổi trong Dokploy environment
      - SESSION_SECRET=${SESSION_SECRET:-change-this-secret-in-dokploy}
      
      # Admin password (chỉ dùng khi tạo users.json lần đầu)
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_DEFAULT_PASSWORD:-admin}
      
      # Webhook URLs
      - MESSAGE_WEBHOOK_URL=${MESSAGE_WEBHOOK_URL}
      - GROUP_EVENT_WEBHOOK_URL=${GROUP_EVENT_WEBHOOK_URL}
      - REACTION_WEBHOOK_URL=${REACTION_WEBHOOK_URL}
      - WEBHOOK_LOGIN_SUCCESS=${WEBHOOK_LOGIN_SUCCESS}
      
      # Proxy config
      - MAX_ACCOUNTS_PER_PROXY=${MAX_ACCOUNTS_PER_PROXY:-3}
    
    restart: always
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits (optional, adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

# Named volumes for persistent data
# QUAN TRỌNG: Dữ liệu trong volume này sẽ được giữ lại khi:
# - Rebuild container
# - Update image  
# - Restart service
# - Redeploy từ Dokploy
volumes:
  multizlogin-data:
    driver: local
